# Task 1:

Given code:

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5]) 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print("1D Array:", arr_1d) 
print("2D Array:\n", arr_2d)

print("Sum of 1D Array:", np.sum(arr_1d)) 
print("Mean of 2D Array:", np.mean(arr_2d)) 
print("Transpose of 2D Array:\n", arr_2d.T)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D Array: 15
Mean of 2D Array: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Task:

In [9]:
arr_1d = np.array([1, 2, 3, 4, 5]) 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def array_operations():
    global arr_1d, arr_2d

    print("1D Array:", arr_1d) 
    print("2D Array:\n", arr_2d)

    print("Sum of 1D Array:", np.sum(arr_1d)) 
    print("Mean of 2D Array:", np.mean(arr_2d)) 
    print("Transpose of 2D Array:\n", arr_2d.T)

array_operations()

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D Array: 15
Mean of 2D Array: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# Task 2

In [10]:
# Creating a grayscale image using a 2D NumPy array 
image = np.random.randint(0, 256, (5, 5), dtype=np.uint8) 

print("Original Image:\n", image) 

# Slicing a portion of the image 
cropped = image[1:4, 1:4] 
print("Cropped Section:\n", cropped) 

# Inverting colors 
inverted_image = 255 - image 
print("Inverted Image:\n", inverted_image)

Original Image:
 [[217 239 193 125   6]
 [172  86 212 222  19]
 [ 41 227 202 179 101]
 [ 90 153 187 201  90]
 [ 99  69  87 241 222]]
Cropped Section:
 [[ 86 212 222]
 [227 202 179]
 [153 187 201]]
Inverted Image:
 [[ 38  16  62 130 249]
 [ 83 169  43  33 236]
 [214  28  53  76 154]
 [165 102  68  54 165]
 [156 186 168  14  33]]


Task:

In [11]:
def image_processing():
    image = np.random.randint(0, 256, (5, 5), dtype=np.uint8) 

    print("Original Image:\n", image) 

    cropped = image[1:4, 1:4] 
    print("Cropped Section:\n", cropped) 

    inverted_image = 255 - image 
    print("Inverted Image:\n", inverted_image)
    
image_processing()

Original Image:
 [[ 36  69 201 177  51]
 [131 248 201  95  96]
 [222  68 243 167 112]
 [112  46 128  84 181]
 [ 23 203 205 201  14]]
Cropped Section:
 [[248 201  95]
 [ 68 243 167]
 [ 46 128  84]]
Inverted Image:
 [[219 186  54  78 204]
 [124   7  54 160 159]
 [ 33 187  12  88 143]
 [143 209 127 171  74]
 [232  52  50  54 241]]


# Task 3:

In [ ]:
import numpy as np 
import cv2 
# Load an image
image = cv2.imread('image.jpg') #Use your own image 
# Scaling Transformation
def scale_image(image, scale_factor): 
    # Create the scaling matrix 
    scaling_matrix = np.array([[scale_factor, 0, 0], [0, scale_factor, 0], [0, 0, 1]]) 
    # Get the image dimensions 
    rows, cols = image.shape[:2] 
    # Apply the transformation 
    scaled_image = cv2.warpPerspective(image, scaling_matrix, (cols, rows)) 
    return scaled_image 
# Rotation Transformation 
def rotate_image(image, angle): 
    # Get the image dimensions 
    rows, cols = image.shape[:2] 
    # Get the rotation matrix 
    rotation_matrix = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 1) 
    # Apply the rotation 
    rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows)) 
    return rotated_image # Translation Transformation def translate_image(image, tx, ty): # Create the translation matrix translation_matrix = np.array([[1, 0, tx], [0, 1, ty], [0, 0, 1]]) # Get the image dimensions rows, cols = image.shape[:2] # Apply the transformation translated_image = cv2.warpPerspective(image, translation_matrix, (cols, rows)) return translated_image # Example transformations
scaled_image = scale_image(image, 1.5) # Scale by a factor of 1.5 rotated_image = rotate_image(image, 45) # Rotate by 45 degrees translated_image = translate_image(image, 50, 30) # Translate by 50 pixels along x and 30 pixels along y # Show the results cv2.imshow('Original', image) cv2.imshow('Scaled', scaled_image) cv2.imshow('Rotated', rotated_image) cv2.imshow('Translated', translated_image) cv2.waitKey(0) cv2.destroyAllWindows()